[package]
name = "richard/clear"
version = "0.0.3"
description = "clears an xterm compatible console"

[[module]]
name = "clear"
source = "clear.wasm"
abi = "wasi"

[[command]]
name = "clear"
module = "clear"