[package]
name = "richard/clear"
version = "0.0.4"
description = "clears an xterm compatible console"
readme = "README.md"
repository = "https://github.com/richardanaya/clear"

[[module]]
name = "clear"
source = "clear.wasm"
abi = "wasi"

[[command]]
name = "clear"
module = "clear"